In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel(r'D:\ITI\FinalProject\data\final.xlsx')
df.head()

,Individual_ID,Family_ID,GOV_CODE,Governorate_Name,Gender,AGE_CODE,Age,Marital_Status_Code,Marital_Status,Region_Type,...,Work_Location_Type,Is_Establishment_Registered,Is_Establishment_Insured,Quarter_ID,AGE_GROUP,Age_Range,Professional_Training_Status,Annual_Weight,Normalized_Factor,Quarterly_Weight
0,31AE82A8-95D7-4E66-876D-8031121996A2,9A9D8DC8-9355-4128-9164-D260852720BF,4,السويس,ذكر,NaN,38,3.0,متزوج/ة,حضر,...,داخل المنشأة,لا - غير مسجل,لا - غير مؤمن,1,سن العمل,30-34 سنة,لا - لم يلتحق,224.842430,0.158556,899.369721
1,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,CB34CB01-2F0E-4C0D-A11D-E6357E8727AF,18,البحيرة,أنثى,1.0,37,3.0,متزوج/ة,ريف,...,NaN,NaN,NaN,1,سن العمل,30-34 سنة,لا - لم يلتحق,383.212208,0.270237,1532.848834
2,189336B9-6857-49C6-836D-C54AC6C2BEE9,068B1966-C39F-4BF2-92DE-1D52C947025D,21,الجيزة,ذكر,1.0,28,1.0,أعزب/عزباء,حضر,...,NaN,NaN,NaN,1,شباب,25-29 سنة,لا - لم يلتحق,431.231027,0.304099,1724.924109
3,1512A995-F9F6-4369-A967-6806B446B1F2,97358DDF-DF60-4406-8C95-0C62B0CF6E01,15,كفر الشيخ,ذكر,2.0,9,NaN,NaN,حضر,...,NaN,NaN,NaN,1,أطفال,15-19 سنة,لا - لم يلتحق,336.670043,0.237416,1346.680171
4,B6AC1F0E-C2AD-458C-BA2A-7A4026C03027,52CDDE65-7225-4717-BB8A-D1F713ADD602,17,المنوفية,أنثى,2.0,80,5.0,أرمل/ة,ريف,...,NaN,NaN,NaN,1,متقاعدين,45-49 سنة,لا - لم يلتحق,200.729200,0.141552,802.916802

In [3]:
df['Labor_Force_Status'].value_counts()

Labor_Force_Status
خارج قوة العمل                   214550
داخل قوة العمل (يعمل أو يبحث)     77543
4                                  3605
3                                  1026
Name: count, dtype: int64

In [4]:
df['Salary_Level_Classification'].value_counts()

Salary_Level_Classification
منخفض    35042
متوسط    23066
مرتفع    16618
4          708
Name: count, dtype: int64

In [12]:
df[['Basic_Salary', 'Salary_Level_Classification']]

        Basic_Salary Salary_Level_Classification
0               3500                       متوسط
1                  0                         NaN
2                  0                         NaN
3                  0                         NaN
4                  0                         NaN
...              ...                         ...
296719             0                         NaN
296720             0                         NaN
296721             0                         NaN
296722           300                       منخفض
296723           300                       منخفض

[296724 rows x 2 columns]